require "set"

HEIGHT = 12
FONT_DIR = "#{File.dirname __FILE__}/../3rd/shinonome-0.9.11-src/#{HEIGHT}"

File.write "shinonome.hxx", <<EOS
#pragma once

#include <cstdint>
#include <array>

namespace shinonome {

static constexpr unsigned HEIGHT = #{HEIGHT};

template<unsigned W>
struct Char {
  static constexpr unsigned WIDTH = W;
  static constexpr unsigned HEIGHT = shinonome::HEIGHT;
  static constexpr unsigned PIXELS = W * HEIGHT;
  char32_t codepoint;
  std::array<uint32_t, PIXELS / 32 + ((PIXELS % 32) > 0 ? 1 : 0)> data;
};

extern const Char<HEIGHT / 2> HANKAKU[];
extern const unsigned HANKAKU_LEN;
extern const Char<HEIGHT / 2> LATIN1[];
extern const unsigned LATIN1_LEN;
extern const Char<HEIGHT> GOTHIC[];
extern const unsigned GOTHIC_LEN;

}
EOS

jis0208_table = {}
File.read(ENV["jis0208_table"], external_encoding: Encoding::UTF_8).each_line do |l|
  s, j, u = l.sub(/#.*/, '').split
  next if s.nil?
  jis0208_table[j.to_i(16)] = u.to_i 16
end

# Dev/build escape hatch, a no-op unless set: SHINONOME_GLYPH_TEXT_FILE names
# a UTF-8 text file (any real corpus -- a game's own exported dialogue/
# database text is the intended use) whose distinct codepoints become an
# allow-list for the "full" (JIS0208 kanji) font face below. Every RPG Maker
# game's dialogue only ever touches a few hundred distinct kanji out of the
# ~7000 JIS0208 defines; embedding the entire table on a target as flash-
# constrained as the Wio Terminal (docs/adr/0104's own real measurement: the
# unfiltered GOTHIC face alone is 165 KB, a third of the board's whole 496 KB
# budget) means shipping thousands of glyphs no game exported today will ever
# draw. This is the general mechanism; nothing calls it with a real file yet
# -- that needs an actual per-game export step (scanning LMU/LMT/LDB text),
# still future work. HANKAKU/LATIN1 are never filtered: both are small,
# bounded charsets (halfwidth kana, Latin-1) needed for basically any game's
# UI regardless of which kanji it uses, unlike JIS0208's own much larger
# range.
glyph_allowlist = nil
if ENV["SHINONOME_GLYPH_TEXT_FILE"]
  glyph_allowlist = File.read(ENV["SHINONOME_GLYPH_TEXT_FILE"], external_encoding: Encoding::UTF_8)
                        .each_codepoint.to_a.uniq.to_set
end

# docs/adr/0110/0112: a second, independent escape hatch (a no-op unless
# set, same convention as SHINONOME_GLYPH_TEXT_FILE above -- build_config.rb
# sets it by default for wio specifically, everywhere else it stays opt-in)
# -- rather than
# *trimming* the GOTHIC (JIS0208 kanji) face's flash cost, moves the whole
# thing to the SD card: every glyph this pass would otherwise emit as a
# compiled-in C array entry is instead packed into a flat binary file
# (u32 glyph_count, then glyph_count * (u32 codepoint, GOTHIC_WORDS * u32
# bitmap data), all little-endian, still sorted by codepoint) that
# mruby-rgss/src/lib.cxx's own find_gothic_char reads back with a plain
# fseek/fread binary search (RGSS_SHINONOME_GOTHIC_SD_PATH) instead of
# find_char's in-memory one. GOTHIC's own compiled-in array still gets
# written -- just empty (GOTHIC_LEN 0) -- so a build that sets this without
# also defining RGSS_SHINONOME_GOTHIC_SD_PATH simply finds no kanji glyphs
# at all rather than failing to compile.
gothic_sd_file = ENV["SHINONOME_GOTHIC_SD_FILE"]

f = File.new "shinonome.cxx", "w"

f.write <<EOS

#include "shinonome.hxx"

namespace shinonome {

EOS

{
  hankaku: ["HANKAKU", "CP932", false],
  kanjic: ["GOTHIC", "JIS0208", true],
  latin1: ["LATIN1", "ISO-8859-1", false],
  # mincho (a second, serif JIS0208 face) is generated by upstream shinonome
  # alongside kanjic/gothic, but nothing in mruby-rgss ever looks it up --
  # RGSS::Font resolves every request to GOTHIC (mruby-rgss/src/lib.cxx's
  # find_char call sites name it explicitly, never MINCHO) -- so it was pure
  # dead weight: declared, generated, and never called anywhere, confirmed by
  # grepping the whole repo. Dropped outright rather than gated, since this
  # is not a target-specific tradeoff -- desktop/PSP/wasm never used it
  # either.
}.each do |k, (name, encoding, full)|
  if File.exist? "#{FONT_DIR}/#{k}/font_src.bit"
    src = File.read "#{FONT_DIR}/#{k}/font_src.bit", external_encoding: Encoding::SJIS
  else
    src = File.read "#{FONT_DIR}/#{k}/font_src_diff.bit", external_encoding: Encoding::SJIS
  end

  t = {}
  c = nil
  bmp = []
  src.each_line do |l|
    if l.start_with? "STARTCHAR"
      c = l.split[1].to_i 16
      if encoding == "JIS0208"
        c = jis0208_table[c]
      else
        begin
          c = c.chr.encode("UTF-8", encoding).codepoints[0]
        rescue EncodingError
          p "Unknonwn char: #{c}"
        end
      end
      raise "Unknown char: #{l}" if c.nil?
    elsif l.start_with? "ENDCHAR"
      raise "Uknown char" if c.nil?
      # Only the JIS0208 (`full`) faces are ever worth subsetting -- see the
      # SHINONOME_GLYPH_TEXT_FILE comment above.
      t[c] = bmp if !full || glyph_allowlist.nil? || glyph_allowlist.include?(c)
      bmp = []
    elsif l.start_with? "BITMAP"
      bmp = []
    else
      bmp << l
    end
  end

  to_sd = gothic_sd_file && name == "GOTHIC"
  sd_out = nil
  if to_sd
    sd_out = File.open(gothic_sd_file, "wb")
    sd_out.write [t.size].pack("V") # glyph_count, little-endian u32
  end

  f.write <<EOS
const unsigned #{name}_LEN = #{to_sd ? 0 : t.size};
const Char<#{full ? "HEIGHT" : "HEIGHT / 2"}> #{name}[] = {
EOS

  t.sort.to_h.each do |u, b|
    b = b.map(&:strip).reduce(&:+)
    words = b.scan(/.{1,32}/).map do |s|
      v = 0
      s.each_char.each_with_index do |p, idx|
        v |= (1 << idx) if p == "@"
      end
      v
    end

    if to_sd
      sd_out.write [u, *words].pack("V*")
      next
    end

    d = words.map { |v| "0x#{v.to_s(16)}" }
    f.write <<EOS
  { 0x#{u.to_s(16)}, {#{d.join(", ")}} },
EOS
  end

  sd_out&.close

  f.write <<EOS
};
EOS
end

f.write <<EOS
}
EOS

f.close
