# frozen_string_literal: true

# Generated by scripts/native_binding_split.rb (ADR 0263); do not edit.
# name => RGSS class => [entry point in include/rgss_construct.hxx, argument kinds].
module NativeDirect
  GENERATED = {
    "==" => {
      "RGSS::Rect" => ["rect_eq_direct", [:value]],
      "RGSS::Color" => ["color_eq_direct", [:value]],
      "RGSS::Tone" => ["tone_eq_direct", [:value]]
    },
    "_begin_load" => {
      "RGSS::Bitmap.singleton" => ["bmp_begin_load_direct", []]
    },
    "_bgm_fade" => {
      "RGSS::Audio.singleton" => ["bgm_fade_direct", [:int]]
    },
    "_bgm_pan" => {
      "RGSS::Audio.singleton" => ["bgm_pan_direct", [:int]]
    },
    "_bgm_pos" => {
      "RGSS::Audio.singleton" => ["bgm_pos_direct", []]
    },
    "_bgm_stop" => {
      "RGSS::Audio.singleton" => ["bgm_stop_direct", []]
    },
    "_bgm_volume" => {
      "RGSS::Audio.singleton" => ["bgm_volume_direct", [:int]]
    },
    "_bgs_fade" => {
      "RGSS::Audio.singleton" => ["bgs_fade_direct", [:int]]
    },
    "_bgs_pos" => {
      "RGSS::Audio.singleton" => ["bgs_pos_direct", []]
    },
    "_bgs_stop" => {
      "RGSS::Audio.singleton" => ["bgs_stop_direct", []]
    },
    "_can_play_mem?" => {
      "RGSS::Audio.singleton" => ["can_play_mem_direct", []]
    },
    "_decoder_ran?" => {
      "RGSS::Bitmap.singleton" => ["bmp_decoder_ran_direct", []]
    },
    "_dump" => {
      "RGSS::Rect" => ["rect_dump_direct", []],
      "RGSS::Color" => ["color_dump_direct", []],
      "RGSS::Tone" => ["tone_dump_direct", []],
      "RGSS::Table" => ["table_dump_direct", []]
    },
    "_init_size" => {
      "RGSS::Bitmap" => ["bmp_init_size_direct", [:int, :int]]
    },
    "_load" => {
      "RGSS::Rect.singleton" => ["rect_s_load_direct", [:str]],
      "RGSS::Color.singleton" => ["color_load_direct", [:str]],
      "RGSS::Tone.singleton" => ["tone_load_direct", [:str]],
      "RGSS::Table.singleton" => ["table_load_direct", [:str]]
    },
    "_load_error" => {
      "RGSS::Bitmap.singleton" => ["bmp_load_error_direct", []]
    },
    "_me_fade" => {
      "RGSS::Audio.singleton" => ["me_fade_direct", [:int]]
    },
    "_me_stop" => {
      "RGSS::Audio.singleton" => ["me_stop_direct", []]
    },
    "_midi_available" => {
      "RGSS::Audio.singleton" => ["midi_available_direct", []]
    },
    "_push" => {
      "RGSS::Input.singleton" => ["input_push_direct", [:int, :bool]]
    },
    "_se_stop" => {
      "RGSS::Audio.singleton" => ["se_stop_direct", []]
    },
    "_stbi_error" => {
      "RGSS::Bitmap.singleton" => ["bmp_stbi_error_direct", []]
    },
    "_transition_alpha" => {
      "RGSS::Bitmap" => ["bmp_transition_alpha_direct", [:value, :float, :float]]
    },
    "_update" => {
      "RGSS::Audio.singleton" => ["audio_update_direct", []]
    },
    "active=" => {
      "RGSS::Window" => ["window_active_set_direct", [:bool]]
    },
    "alpha" => {
      "RGSS::Color" => ["color_alpha_direct", []]
    },
    "angle=" => {
      "RGSS::Sprite" => ["spr_set_angle_direct", [:float]]
    },
    "available?" => {
      "RGSS::Tts.singleton" => ["tts_available_direct", []]
    },
    "back_opacity=" => {
      "RGSS::Window" => ["window_set_back_opacity_direct", [:int]]
    },
    "bitmap=" => {
      "RGSS::Sprite" => ["sprite_bitmap_set_direct", [:value]],
      "RGSS::Plane" => ["plane_set_bmp_direct", [:value]]
    },
    "bitmaps" => {
      "RGSS::Tilemap" => ["tilemap_bitmaps_direct", []]
    },
    "blend_type=" => {
      "RGSS::Sprite" => ["spr_set_blend_type_direct", [:int]],
      "RGSS::Plane" => ["spr_set_blend_type_direct", [:int]]
    },
    "blue" => {
      "RGSS::Color" => ["color_blue_direct", []],
      "RGSS::Tone" => ["tone_blue_direct", []]
    },
    "blur" => {
      "RGSS::Bitmap" => ["bmp_blur_direct", []]
    },
    "bush_depth=" => {
      "RGSS::Sprite" => ["spr_set_bush_depth_direct", [:int]]
    },
    "clear" => {
      "RGSS::Bitmap" => ["bitmap_clear_direct", []]
    },
    "color" => {
      "RGSS::Viewport" => ["viewport_color_direct", []]
    },
    "color=" => {
      "RGSS::Viewport" => ["viewport_color_set_direct", [:value]],
      "RGSS::Sprite" => ["sprite_color_set_direct", [:value]],
      "RGSS::Plane" => ["plane_color_set_direct", [:value]]
    },
    "contents=" => {
      "RGSS::Window" => ["window_contents_set_direct", [:value]]
    },
    "contents_opacity=" => {
      "RGSS::Window" => ["window_set_contents_opacity_direct", [:int]]
    },
    "cursor_rect=" => {
      "RGSS::Window" => ["window_cursor_rect_set_direct", [:value]]
    },
    "default_font_path" => {
      "RGSS.singleton" => ["default_font_path_m_direct", []]
    },
    "dim" => {
      "RGSS::Table" => ["table_dim_direct", []]
    },
    "dispose" => {
      "RGSS::Viewport" => ["dispose_direct", []],
      "RGSS::Sprite" => ["dispose_direct", []],
      "RGSS::Plane" => ["dispose_direct", []],
      "RGSS::Tilemap" => ["tilemap_dispose_direct", []],
      "RGSS::Window" => ["dispose_direct", []],
      "RGSS::Bitmap" => ["dispose_direct", []]
    },
    "disposed?" => {
      "RGSS::Viewport" => ["disposed_direct", []],
      "RGSS::Sprite" => ["disposed_direct", []],
      "RGSS::Plane" => ["disposed_direct", []],
      "RGSS::Tilemap" => ["disposed_direct", []],
      "RGSS::Window" => ["disposed_direct", []],
      "RGSS::Bitmap" => ["disposed_direct", []]
    },
    "empty" => {
      "RGSS::Rect" => ["rect_empty_direct", []]
    },
    "flags=" => {
      "RGSS::Tilemap" => ["tilemap_set_flags_direct", [:value]]
    },
    "flash" => {
      "RGSS::Viewport" => ["viewport_flash_direct", [:value, :int]],
      "RGSS::Sprite" => ["sprite_flash_direct", [:value, :int]]
    },
    "frame_reset" => {
      "RGSS::Graphics.singleton" => ["gfx_frame_reset_direct", []]
    },
    "gray" => {
      "RGSS::Tone" => ["tone_gray_direct", []]
    },
    "green" => {
      "RGSS::Color" => ["color_green_direct", []],
      "RGSS::Tone" => ["tone_green_direct", []]
    },
    "height" => {
      "RGSS::Rect" => ["rect_height_direct", []],
      "RGSS::Bitmap" => ["bitmap_height_direct", []]
    },
    "height=" => {
      "RGSS::Rect" => ["rect_height_set_direct", [:int]],
      "RGSS::Window" => ["window_height_set_direct", [:int]]
    },
    "initialize_copy" => {
      "RGSS::Bitmap" => ["bmp_init_copy_direct", [:value]]
    },
    "map_data=" => {
      "RGSS::Tilemap" => ["tilemap_set_map_data_direct", [:value]]
    },
    "mirror=" => {
      "RGSS::Sprite" => ["spr_set_mirror_direct", [:bool]]
    },
    "mouse_pressed?" => {
      "RGSS.singleton" => ["mouse_pressed_m_direct", []]
    },
    "mouse_x" => {
      "RGSS.singleton" => ["mouse_x_m_direct", []]
    },
    "mouse_y" => {
      "RGSS.singleton" => ["mouse_y_m_direct", []]
    },
    "opacity=" => {
      "RGSS::Sprite" => ["spr_set_opacity_direct", [:int]],
      "RGSS::Plane" => ["spr_set_opacity_direct", [:int]],
      "RGSS::Window" => ["window_set_opacity_direct", [:int]]
    },
    "openness=" => {
      "RGSS::Window" => ["window_set_openness_direct", [:int]]
    },
    "ox" => {
      "RGSS::Viewport" => ["vp_ox_direct", []]
    },
    "ox=" => {
      "RGSS::Viewport" => ["vp_set_ox_direct", [:int]],
      "RGSS::Plane" => ["plane_set_ox_direct", [:int]],
      "RGSS::Tilemap" => ["tilemap_set_ox_direct", [:int]],
      "RGSS::Window" => ["window_set_ox_direct", [:int]]
    },
    "oy" => {
      "RGSS::Viewport" => ["vp_oy_direct", []]
    },
    "oy=" => {
      "RGSS::Viewport" => ["vp_set_oy_direct", [:int]],
      "RGSS::Plane" => ["plane_set_oy_direct", [:int]],
      "RGSS::Tilemap" => ["tilemap_set_oy_direct", [:int]],
      "RGSS::Window" => ["window_set_oy_direct", [:int]]
    },
    "pause=" => {
      "RGSS::Window" => ["window_pause_set_direct", [:bool]]
    },
    "priorities=" => {
      "RGSS::Tilemap" => ["tilemap_set_priorities_direct", [:value]]
    },
    "rect" => {
      "RGSS::Viewport" => ["viewport_rect_direct", []],
      "RGSS::Bitmap" => ["bitmap_rect_direct", []]
    },
    "rect=" => {
      "RGSS::Viewport" => ["vp_set_rect_direct", [:value]]
    },
    "red" => {
      "RGSS::Color" => ["color_red_direct", []],
      "RGSS::Tone" => ["tone_red_direct", []]
    },
    "speak" => {
      "RGSS::Tts.singleton" => ["tts_speak_direct", [:cstr]]
    },
    "src_rect=" => {
      "RGSS::Sprite" => ["spr_set_src_rect_direct", [:value]]
    },
    "stop" => {
      "RGSS::Tts.singleton" => ["tts_stop_direct", []]
    },
    "stretch=" => {
      "RGSS::Window" => ["window_set_stretch_direct", [:bool]]
    },
    "text_size" => {
      "RGSS::Bitmap" => ["bmp_text_size_direct", [:str]]
    },
    "tileset=" => {
      "RGSS::Tilemap" => ["tilemap_set_tileset_direct", [:value]]
    },
    "to_s" => {
      "RGSS::Rect" => ["rect_to_s_direct", []],
      "RGSS::Color" => ["color_to_s_direct", []],
      "RGSS::Tone" => ["tone_to_s_direct", []]
    },
    "tone" => {
      "RGSS::Viewport" => ["viewport_tone_direct", []],
      "RGSS::Window" => ["window_tone_direct", []]
    },
    "tone=" => {
      "RGSS::Viewport" => ["vp_set_tone_direct", [:value]],
      "RGSS::Sprite" => ["spr_set_tone_direct", [:value]],
      "RGSS::Plane" => ["plane_set_tone_direct", [:value]],
      "RGSS::Window" => ["window_set_tone_direct", [:value]]
    },
    "update" => {
      "RGSS::Viewport" => ["viewport_update_direct", []],
      "RGSS::Sprite" => ["sprite_update_direct", []],
      "RGSS::Tilemap" => ["tilemap_update_direct", []],
      "RGSS::Window" => ["window_update_direct", []]
    },
    "viewport=" => {
      "RGSS::Window" => ["window_set_viewport_direct", [:value]]
    },
    "visible" => {
      "RGSS::Viewport" => ["visible_direct", []],
      "RGSS::Sprite" => ["visible_direct", []],
      "RGSS::Plane" => ["visible_direct", []],
      "RGSS::Tilemap" => ["visible_direct", []],
      "RGSS::Window" => ["visible_direct", []]
    },
    "visible=" => {
      "RGSS::Viewport" => ["object_visible_set_direct", [:bool]],
      "RGSS::Sprite" => ["object_visible_set_direct", [:bool]],
      "RGSS::Plane" => ["object_visible_set_direct", [:bool]],
      "RGSS::Tilemap" => ["tilemap_visible_set_direct", [:bool]],
      "RGSS::Window" => ["object_visible_set_direct", [:bool]]
    },
    "vx_table_leg_quads" => {
      "RGSS::Tilemap.singleton" => ["tilemap_vx_table_leg_quads_direct", [:int]]
    },
    "width" => {
      "RGSS::Rect" => ["rect_width_direct", []],
      "RGSS::Bitmap" => ["bitmap_width_direct", []]
    },
    "width=" => {
      "RGSS::Rect" => ["rect_width_set_direct", [:int]],
      "RGSS::Window" => ["window_width_set_direct", [:int]]
    },
    "window_title" => {
      "RGSS.singleton" => ["window_title_get_m_direct", []]
    },
    "window_title=" => {
      "RGSS.singleton" => ["window_title_set_m_direct", [:value]]
    },
    "windowskin=" => {
      "RGSS::Window" => ["window_windowskin_set_direct", [:value]]
    },
    "x" => {
      "RGSS::Rect" => ["rect_x_direct", []]
    },
    "x=" => {
      "RGSS::Rect" => ["rect_x_set_direct", [:int]],
      "RGSS::Sprite" => ["object_x_set_direct", [:int]],
      "RGSS::Window" => ["object_x_set_direct", [:int]]
    },
    "xsize" => {
      "RGSS::Table" => ["table_xsize_direct", []]
    },
    "y" => {
      "RGSS::Rect" => ["rect_y_direct", []]
    },
    "y=" => {
      "RGSS::Rect" => ["rect_y_set_direct", [:int]],
      "RGSS::Sprite" => ["object_y_set_direct", [:int]],
      "RGSS::Window" => ["object_y_set_direct", [:int]]
    },
    "ysize" => {
      "RGSS::Table" => ["table_ysize_direct", []]
    },
    "z=" => {
      "RGSS::Viewport" => ["object_z_set_direct", [:int]],
      "RGSS::Sprite" => ["object_z_set_direct", [:int]],
      "RGSS::Plane" => ["object_z_set_direct", [:int]],
      "RGSS::Tilemap" => ["tilemap_z_set_direct", [:int]],
      "RGSS::Window" => ["object_z_set_direct", [:int]]
    },
    "zlib_inflate" => {
      "RGSS.singleton" => ["zlib_inflate_direct", [:str]]
    },
    "zoom_x=" => {
      "RGSS::Sprite" => ["spr_set_zoom_x_direct", [:float]],
      "RGSS::Plane" => ["plane_set_zoom_x_direct", [:float]]
    },
    "zoom_y=" => {
      "RGSS::Sprite" => ["spr_set_zoom_y_direct", [:float]],
      "RGSS::Plane" => ["plane_set_zoom_y_direct", [:float]]
    },
    "zsize" => {
      "RGSS::Table" => ["table_zsize_direct", []]
    }
  }.freeze
end
