#!/usr/bin/env ruby
# encoding: UTF-8
# Check OUTLINED_INDEX_OPS (tools/bc2cpp/bc2cpp.rb, docs/adr/0216): an untyped
# GETIDX/GETIDX0/SETIDX site calls one file-scope helper (bc2cpp_getidx /
# bc2cpp_getidx0 / bc2cpp_setidx) instead of repeating the generic
# Array/Hash/String/POLY_SMALL_N chain inline.
#
# 1. Codegen: a generic site is one helper call; a literal-Symbol site keeps
#    its per-site Struct branches and calls the helper in the else arm; a
#    method that installs `[]` at runtime keeps the whole chain inline; the
#    helper's POLY_SMALL_N arm names every compiled `#[]` and ends in the
#    by-name fallback, which the static-dispatch scan still sees as a use of
#    `[]`; a file with no index op emits no helper.
# 2. Runtime: a fixture is generated by the real bc2cpp.rb pipeline, compiled
#    against real mruby and every case is run twice, first as bytecode and
#    then with the compiled methods registered. Result, receiver and raised
#    error must match exactly, and the compiled run must make exactly the
#    expected number of by-name dispatches. Needs BC2CPP_MRUBY_CORE
#    (libmruby_core.a + include/) and g++; skipped without them.
#
# Usage: MRBC=path/to/mrbc [BC2CPP_MRUBY_CORE=build/mruby/host/mrbc] \
#          ruby scripts/bc2cpp_outlined_index_check.rb

require 'open3'
require 'shellwords'
require 'tmpdir'
require_relative '../tools/bc2cpp/bc2cpp'
require_relative '../tools/bc2cpp/compiled_gems'
require_relative '../tools/bc2cpp/static_dispatch_registrations'

ROOT = File.expand_path('..', __dir__)
BC2CPP = File.join(ROOT, 'tools/bc2cpp/bc2cpp.rb')

failures = []
check = lambda do |what, condition|
  puts "  #{condition ? 'ok  ' : 'FAIL'} #{what}"
  failures << what unless condition
end

# Runs the real bc2cpp.rb driver over `source`; returns [generated C++, stderr, dir].
def run_bc2cpp(source, dir)
  src = File.join(dir, 'fixture.rb')
  File.write(src, source)
  out, err, status = Open3.capture3({ 'MRBC' => MRBC, 'SKIP_UNSUPPORTED' => '1', 'OUT_SYMBOL' => 'fixture',
                                      'OUT_DIR' => dir, 'BC2CPP_SELF_REGISTERING' => '1',
                                      'NATIVE_SRCS' => Shellwords.join(core_native_srcs("#{ROOT}/3rd/mruby")) },
                                    RbConfig.ruby, BC2CPP, src)
  abort "bc2cpp.rb failed:\n#{err[-2000..]}" unless status.success?
  [out, err]
end

# The C++ function `name` in `code` (its signature line through the closing brace at column 0).
def function_text(code, name)
  start = code.index(/^static mrb_value #{Regexp.escape(name)}\(/) or return nil
  code[start..code.index(/^\}\n/, start)]
end

# --- 1. codegen ---------------------------------------------------------------
puts '-- codegen'
CODEGEN = <<~'RUBY'
  class Vars
    def [](id); id * 2; end
  end
  class Grid
    def [](id); id + 100; end
  end
  class Probe
    def get(x, i); x[i]; end
    def get0(x); x[0]; end
    def set(x, i, v); x[i] = v; end
    def left(x); x[:left]; end
  end
  class Patcher
    def patch(o)
      def o.[](k); k; end
      o[1]
    end
  end
RUBY

Dir.mktmpdir do |dir|
  path = File.join(dir, 'codegen.rb')
  File.write(path, CODEGEN)
  c_dump, disasm = run_mrbc(path, 'bc2cpp_outlined_index', dir)
  ireps, root_label = parse_c_dump(c_dump, 'bc2cpp_outlined_index')
  blocks, block_files, block_catches = parse_disasm_blocks(disasm)
  merge!(ireps, dfs_order(ireps, root_label), blocks, block_files, block_catches)
  registry, superclass_of, _containers, included, prepended, unknown_mixins = build_registry(ireps, root_label)
  CodeGen.struct_members = { 'Pair' => %w[left right] }
  gen = CodeGen.new(ireps, registry, {}, {}, {}, {}, superclass_of, {}, {}, {}, {}, Set.new, nil, nil, nil,
                    included, prepended, unknown_mixins)
  code_of = ->(owner, meth) { gen.compile_method(registry.fetch(meth).find { |d| d.owner == owner }.irep).fetch(:code) }

  get = code_of.call('Probe', 'get')
  check.call('a generic GETIDX site is one helper call, with no inline chain',
             get.match?(/^\s*r(\d+) = bc2cpp_getidx\(M, r\1, r\d+\);$/) &&
               !get.include?('mrb_hash_get') && !get.include?('POLY_SMALL_N') && !get.include?('"[]"'))
  get0 = code_of.call('Probe', 'get0')
  check.call('a generic GETIDX0 site is one helper call',
             get0.match?(/^\s*r\d+ = bc2cpp_getidx0\(M, r\d+\);$/) && !get0.include?('mrb_hash_get'))
  set = code_of.call('Probe', 'set')
  check.call('a generic SETIDX site is one helper call',
             set.match?(/^\s*r(\d+) = bc2cpp_setidx\(M, r\1, r\d+, r\d+\);$/) && !set.include?('mrb_hash_set'))

  left = code_of.call('Probe', 'left')
  struct_at = left.index('MRB_TT_STRUCT')
  helper_at = left.index('bc2cpp_getidx(M,')
  check.call('a literal-Symbol site keeps its Struct branch inline and calls the helper in the else arm',
             struct_at && helper_at && struct_at < helper_at &&
               left.match?(/RARRAY_PTR\(r\d+\)\[0\] : mrb_nil_value\(\);\n\s*\} else \{\n\s*r(\d+) = bc2cpp_getidx\(M, r\1, r\d+\);/) &&
               !left.include?('mrb_hash_get'))

  patch = code_of.call('Patcher', 'patch')
  check.call('a method installing `[]` at runtime keeps the inline chain and never calls the helper',
             patch.include?('#error') || (!patch.include?('bc2cpp_getidx(') && patch.include?('mrb_hash_get(M,') &&
                                          !patch.include?('POLY_SMALL_N :[]')))

  helpers = gen.emit_index_helpers([{ code: get + get0 + set }])
  getidx = function_text(helpers, 'bc2cpp_getidx')
  check.call('the GETIDX helper keeps the Array, Hash, String order of the old chain',
             getidx && getidx.index('M->array_class') < getidx.index('M->hash_class') &&
               getidx.index('M->hash_class') < getidx.index('M->string_class') &&
               getidx.index('M->string_class') < getidx.index('POLY_SMALL_N :[]'))
  check.call('its POLY_SMALL_N arm calls every compiled #[] and ends in the by-name fallback',
             getidx && getidx.include?('POLY_SMALL_N :[] -> Vars, Grid') &&
               getidx.match?(/r0 = Vars_\w+_impl\(M, recv, key\);/) && getidx.match?(/r0 = Grid_\w+_impl\(M, recv, key\);/) &&
               getidx.include?('r0 = mrb_funcall(M, recv, "[]", 1, key);'))
  getidx0 = function_text(helpers, 'bc2cpp_getidx0')
  check.call('the GETIDX0 helper keeps its own Array/Hash/funcall chain (no String or POLY arm)',
             getidx0 && getidx0.include?('bc2cpp_ary_entry(M, recv, 0)') &&
               getidx0.include?('mrb_hash_get(M, recv, mrb_fixnum_value(0))') &&
               getidx0.include?('mrb_funcall(M, recv, "[]", 1, mrb_fixnum_value(0))') && !getidx0.include?('string_class'))
  setidx = function_text(helpers, 'bc2cpp_setidx')
  check.call('the SETIDX helper returns the assigned value on the fast paths and the method result otherwise',
             setidx && setidx.scan('return val;').size == 2 && setidx.include?('return mrb_funcall(M, recv, "[]=", 2, idx, val);'))
  check.call('only the helpers a file calls are emitted',
             gen.emit_index_helpers([{ code: get }]).then { |h| h.include?('bc2cpp_getidx(') && !h.include?('bc2cpp_setidx(') } &&
               gen.emit_index_helpers([{ code: 'r1 = r2;' }]).empty?)
end

# --- 2. real mruby -------------------------------------------------------------
RUNTIME = <<~'RUBY'
  class Vars
    def [](id); id * 2; end
    def []=(k, v); k + v; end
    def inspect; '#<Vars>'; end
  end
  class Grid
    def [](id); id + 100; end
    def inspect; '#<Grid>'; end
  end
  class SubArray < Array
  end
  class Make
    def self.recv(n)
      case n
      when 0 then [10, 20, 30]
      when 1 then { 1 => 'a', 0 => 'z' }
      when 2 then 'hello'
      when 3 then Vars.new
      when 4 then Grid.new
      when 5 then SubArray.new
      when 6 then Object.new
      else nil
      end
    end

    def self.key(n)
      case n
      when 0 then 1
      when 1 then -1
      when 2 then 5
      when 3 then 0..1
      when 4 then 'll'
      when 5 then 21
      when 6 then :sym
      else 0
      end
    end
  end
  class Probe
    def get(x, i); x[i]; end
    def get0(x); x[0]; end
    def set(x, i, v); x[i] = v; end
  end
RUBY

# [method, receiver, key, compiled by-name dispatches expected]
CASES = [
  ['get', 0, 0, 0], ['get', 0, 1, 0], ['get', 0, 2, 0], ['get', 0, 3, 1],
  ['get', 1, 0, 0], ['get', 1, 6, 0],
  ['get', 2, 0, 0], ['get', 2, 4, 0], ['get', 2, 3, 0], ['get', 2, 6, 1],
  ['get', 3, 5, 0], ['get', 4, 0, 0], ['get', 5, 0, 1], ['get', 6, 0, 1], ['get', 7, 0, 1],
  ['get0', 0, 0, 0], ['get0', 1, 0, 0], ['get0', 2, 0, 1], ['get0', 3, 0, 1], ['get0', 6, 0, 1],
  ['set', 0, 0, 0], ['set', 0, 3, 1], ['set', 1, 6, 0], ['set', 3, 5, 1], ['set', 6, 0, 1]
].freeze

puts '-- fixture on real mruby'
core = [ENV['BC2CPP_MRUBY_CORE'], *Dir[File.join(ROOT, 'build*/mruby/host/mrbc')]].compact.find do |dir|
  File.exist?(File.join(dir, 'lib/libmruby_core.a')) && File.directory?(File.join(dir, 'include'))
end
Dir.mktmpdir do |dir|
  out, err = run_bc2cpp(RUNTIME, dir)
  File.write(File.join(dir, 'fixture_gen.cpp'), out)
  %w[bc2cpp_getidx bc2cpp_getidx0 bc2cpp_setidx].each do |h|
    check.call("#{h} is defined exactly once in the generated file",
               out.scan(/^static mrb_value #{h}\(/).size == 1)
  end
  check.call('its by-name fallbacks go through the symbol cache like every other send',
             !function_text(out, 'bc2cpp_getidx').include?('mrb_funcall(') &&
               function_text(out, 'bc2cpp_getidx').match?(/r0 = bc2cpp_send\(M, recv, \d+, 1, key\);/))
  literals = StaticDispatchRegistrations.c_literals(out)
  check.call('the static-dispatch scan still counts `[]` and `[]=` as dynamic uses',
             literals.include?('[]') && literals.include?('[]='))
  check.call('the stderr summary counts the outlined sites', err.match?(/== outlined index ops: getidx \d+/))

  empty_dir = File.join(dir, 'empty')
  Dir.mkdir(empty_dir)
  empty, = run_bc2cpp("class Plain\n  def two; 1 + 1; end\nend\n", empty_dir)
  check.call('a file with no index op emits no helper', !empty.include?('bc2cpp_getidx') && !empty.include?('bc2cpp_setidx'))

  if core.nil? || !system('g++', '--version', out: File::NULL, err: File::NULL)
    puts '  SKIP run: no libmruby_core.a with include/ found (set BC2CPP_MRUBY_CORE)'
    next
  end

  entries = err.split('== compiled entry points ==', 2)[1].to_s.split("\n== ", 2)[0]
               .scan(%r{^\s+(\w+) / \w+\s+\(([^#]+)#([^,]+), arity \d+\)(.*)$})
  registrations = entries.map do |entry, owner, name, extra|
    klass = "mrb_class_ptr(mrb_const_get(M, mrb_obj_value(M->object_class), mrb_intern_cstr(M, #{owner.delete_suffix('.singleton').dump})))"
    fn = if owner.end_with?('.singleton') then 'mrb_define_class_method'
         elsif extra.include?('[private') then 'mrb_define_private_method'
         else 'mrb_define_method'
         end
    "  #{fn}(M, #{klass}, #{name.dump}, #{entry}, MRB_ARGS_ANY());"
  end
  check.call('every Probe method was compiled', %w[get get0 set].all? { |m| entries.any? { |_, o, n, _| o == 'Probe' && n == m } })
  cases = CASES.map { |m, r, k, n| "  { #{m.dump}, #{r}, #{k}, #{n} }," }
  File.write(File.join(dir, 'main.cpp'), <<~CPP)
    #include <mruby.h>
    static int dispatches = 0;
    // bc2cpp_send and the helpers' fallbacks all end in mrb_funcall_argv.
    #define mrb_funcall_argv(M, ...) (++dispatches, (mrb_funcall_argv)(M, __VA_ARGS__))
    #include "fixture_gen.cpp"
    #include <mruby/irep.h>
    #include <mruby/string.h>
    #include <cstdio>
    #include <fstream>
    #include <iterator>
    #include <string>
    #include <vector>
    extern "C" void mrb_init_mrblib(mrb_state*) {}
    struct Case { const char* meth; int recv, key, want_dispatches; };
    static const Case kCases[] = {
    #{cases.join("\n")}
    };
    static std::string show(mrb_state* M, mrb_value v) {
      mrb_value s = (mrb_funcall)(M, v, "inspect", 0);
      return std::string(RSTRING_PTR(s), RSTRING_LEN(s));
    }
    static mrb_value make(mrb_state* M, const char* what, int n) {
      return (mrb_funcall)(M, mrb_obj_value(mrb_class_get(M, "Make")), what, 1, mrb_fixnum_value(n));
    }
    // One case: what the call returned (or raised), and the receiver after it.
    // mrb_init_mrblib is stubbed, so a NoMethodError surfaces as mruby's
    // "exception corrupted" Exception -- identically in both runs.
    static std::string run(mrb_state* M, const Case& c, int* used) {
      mrb_value recv = make(M, "recv", c.recv);
      mrb_value key = make(M, "key", c.key);
      mrb_value probe = mrb_obj_new(M, mrb_class_get(M, "Probe"), 0, nullptr);
      std::string meth = c.meth;
      dispatches = 0;
      mrb_value got = meth == "get0" ? (mrb_funcall)(M, probe, c.meth, 1, recv)
                    : meth == "get"  ? (mrb_funcall)(M, probe, c.meth, 2, recv, key)
                                     : (mrb_funcall)(M, probe, c.meth, 3, recv, key, mrb_fixnum_value(7));
      *used = dispatches;
      std::string r;
      if (M->exc) {
        mrb_value e = mrb_obj_value(M->exc);
        M->exc = nullptr;
        mrb_value msg = (mrb_funcall)(M, e, "message", 0);
        r = std::string("raised ") + mrb_obj_classname(M, e) + ": " + std::string(RSTRING_PTR(msg), RSTRING_LEN(msg));
      } else {
        r = show(M, got);
      }
      if (meth == "set" && c.recv != 6) r += " / receiver " + show(M, recv);
      return r;
    }
    int main(int, char** argv) {
      mrb_state* M = mrb_open_core();
      std::ifstream in(argv[1], std::ios::binary);
      std::vector<uint8_t> bin((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
      mrb_load_irep_buf(M, bin.data(), bin.size());
      if (M->exc) { mrb_print_error(M); return 2; }
      bc2cpp_set_instance_tts(M);
      std::vector<std::string> interpreted;
      int unused;
      for (const Case& c : kCases) interpreted.push_back(run(M, c, &unused));
    #{registrations.join("\n")}
      int failed = 0, i = 0;
      for (const Case& c : kCases) {
        int used = 0;
        std::string compiled = run(M, c, &used);
        bool ok = compiled == interpreted[i] && used == c.want_dispatches;
        std::printf("  %s %s(recv %d, key %d) -> %s (%d by-name dispatch, %d expected)\\n", ok ? "ok  " : "FAIL",
                    c.meth, c.recv, c.key, compiled.c_str(), used, c.want_dispatches);
        if (compiled != interpreted[i]) std::printf("       interpreter: %s\\n", interpreted[i].c_str());
        failed += !ok;
        ++i;
      }
      mrb_close(M);
      return failed ? 1 : 0;
    }
  CPP
  binary = File.join(dir, 'fixture')
  built = system('g++', '-std=c++17', '-fexceptions', '-DMRB_USE_CXX_EXCEPTION', '-DMRB_NO_GEMS', '-w',
                 "-I#{dir}", "-I#{core}/include", "-I#{ROOT}/3rd/mruby/include", "-I#{ROOT}/mruby-rgss/src",
                 File.join(dir, 'main.cpp'), "#{core}/lib/libmruby_core.a", '-lm', '-o', binary)
  check.call('the fixture compiles against real mruby', built)
  if built
    output = IO.popen([binary, File.join(dir, 'fixture.mrb')], err: %i[child out], &:read)
    puts output
    check.call('every compiled case matches the interpreter with the expected by-name dispatches', $?.success?)
  end
end

if failures.empty?
  puts 'bc2cpp outlined index check: PASS'
else
  warn "bc2cpp outlined index check: #{failures.size} failure(s)"
  exit 1
end
