#!/usr/bin/env bash

set -eu -o pipefail

# Fetch the FreePats General MIDI patch set into assets/timidity, where
# src/sdl_audio.cxx looks for it.
#
# A .mid carries note events and no audio, so SDL_mixer's built-in TiMidity
# synthesiser needs a GUS patch (.pat) per General MIDI program to make any
# sound; with none, MIDI music loads successfully and then plays silence. The
# patch set is ~32 MiB of sample data, so it is downloaded here rather than
# committed — the repository stays small and nothing redistributes it.
#
# Source: the `freepats` npm package, which republishes the Old FreePats
# General MIDI sound set from https://freepats.zenvoid.org/. The npm tarball is
# used because it is immutable, version-pinned and checksummable; the upstream
# site serves a rolling archive. FreePats is GPL v2 — the licence lands in
# assets/timidity/LICENSE and must travel with the patches.
#
# Idempotent: re-running with the patches already in place does nothing. Pass
# --force to re-download and overwrite.

version="1.0.3"
sha256="47911ccd41ac4285b001c25ebaf3df6f488d68bd5d8a46355e98505868a9af78"
url="https://registry.npmjs.org/freepats/-/freepats-${version}.tgz"

# Routes through the optional CI CORS proxy cache when CORS_PROXY_URL is set.
. "$(dirname "$0")/cors-proxy-url.bash"

here="$(cd "$(dirname "$0")/.." && pwd)"
dest="$here/assets/timidity"
cache="$here/assets/.freepats"
tarball="$cache/freepats-${version}.tgz"

force=0
[ "${1:-}" = "--force" ] && force=1

if [ "$force" -eq 0 ] && [ -f "$dest/timidity.cfg" ]; then
    echo "freepats: already present in $dest (pass --force to re-download)"
    exit 0
fi

mkdir -p "$cache"

# Re-use a cached tarball only when it matches the pinned checksum; a truncated
# download from an interrupted run must not be trusted.
if [ -f "$tarball" ] && ! echo "$sha256  $tarball" | sha256sum -c --status; then
    echo "freepats: cached tarball failed checksum, re-downloading" >&2
    rm -f "$tarball"
fi

if [ ! -f "$tarball" ]; then
    echo "freepats: downloading $url"
    curl -fsSL --retry 3 --retry-delay 2 -o "$tarball.part" "$(proxied_url "$url")"
    mv "$tarball.part" "$tarball"
fi

# Verify before unpacking: these files are fed to a synthesiser that parses
# binary patch headers, so a corrupt archive would surface as confusing audio
# failures rather than a download error.
echo "$sha256  $tarball" | sha256sum -c --status || {
    echo "freepats: checksum mismatch for $tarball" >&2
    echo "expected $sha256" >&2
    echo "actual   $(sha256sum "$tarball" | cut -d' ' -f1)" >&2
    exit 1
}

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
tar xzf "$tarball" -C "$work"
pkg="$work/package"

for required in freepats.cfg LICENSE Tone_000 Drum_000; do
    if [ ! -e "$pkg/$required" ]; then
        echo "freepats: archive is missing $required" >&2
        exit 1
    fi
done

mkdir -p "$dest"
rm -rf "$dest/Tone_000" "$dest/Drum_000"
cp -r "$pkg/Tone_000" "$pkg/Drum_000" "$dest/"
cp "$pkg/LICENSE" "$dest/LICENSE"

# Write the config with a header explaining what it is. The body is FreePats'
# freepats.cfg unchanged: instrument paths stay relative because SDL_mixer's
# TiMidity adds this file's own directory to its patch search path
# (init_begin_config() in src/codecs/timidity/timidity.c).
{
    cat <<'EOF'
# TiMidity configuration for the FreePats General MIDI patch set.
#
# GENERATED by scripts/download-freepats.bash -- edits here are lost on the next
# run. The body below is FreePats' freepats.cfg verbatim.
#
# SDL_mixer's built-in TiMidity synthesiser reads this file to learn which GUS
# patch (.pat) backs each General MIDI program and drum note; without it, MIDI
# BGM/ME load but play silence. src/sdl_audio.cxx locates this file at startup
# and hands it to SDL_mixer (Mix_SetTimidityCfg / the TIMIDITY_CFG env var).
#
# The instrument paths below are relative to this file's directory, so
# timidity.cfg, Tone_000/ and Drum_000/ must stay siblings. Set TIMIDITY_CFG to
# override this file with a different patch set; sdl_audio.cxx leaves an
# existing TIMIDITY_CFG untouched, so it always wins.
#
# See assets/timidity/README.md for provenance and LICENSE (GPL v2) for terms.
EOF
    cat "$pkg/freepats.cfg"
} > "$dest/timidity.cfg"

echo "freepats: installed into $dest"
ruby "$here/scripts/check_timidity_patches.rb" "$dest"
