#!/usr/bin/env bash
# Builds a FAT-formatted disk image for the Wio Terminal Renode platform's
# SD card model (docs/adr/0094 P4) and a ready-to-include .repl snippet
# that wires it onto sercom6_spi -- the emulated equivalent of exporting a
# map and copying it onto a real microSD card
# (app/wio/renode/README.md's other half is how scripts/wio_sd_upload.py
# does the same thing for real hardware).
#
# Needs mkfs.vfat/mkfs.fat and mtools' mcopy/mmd. If neither is on PATH,
# falls back to `nix-shell -p dosfstools mtools` (this repo's own devshell
# already provides both, so this is only a fallback for a bare environment).
#
# Usage:
#   scripts/wio_renode_sdcard.bash OUT_DIR FILE:CARD_PATH [FILE:CARD_PATH ...]
# Example (the wio_walk map export, mirroring app/wio/README.md's
# --target wio example):
#   ruby scripts/export_nano7_map.rb --target wio \
#     data/Nepheshel206beta/Nepheshel206Nbeta 1 /tmp/rpg2k_walk_out
#   scripts/wio_renode_sdcard.bash /tmp/wio_renode_sdcard \
#     /tmp/rpg2k_walk_out/map.bin:/RPG2kWalk/map.bin \
#     /tmp/rpg2k_walk_out/tiles.bin:/RPG2kWalk/tiles.bin
# Then, after `machine LoadPlatformDescription @app/wio/renode/wio_terminal.repl`:
#   machine LoadPlatformDescription @/tmp/wio_renode_sdcard/sdcard.repl
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "usage: $0 OUT_DIR FILE:CARD_PATH [FILE:CARD_PATH ...]" >&2
  exit 1
fi

out_dir="$1"; shift
mkdir -p "$out_dir"
img="$out_dir/sdcard.img"
size_mb=16

run() {
  if command -v mkfs.vfat >/dev/null 2>&1 && command -v mcopy >/dev/null 2>&1; then
    "$@"
  else
    nix-shell -p dosfstools mtools --run "$(printf '%q ' "$@")"
  fi
}

dd if=/dev/zero of="$img" bs=1M count="$size_mb" status=none
run mkfs.vfat -F 16 -n WIOSD "$img" >/dev/null

made_dirs=()
for spec in "$@"; do
  card_path="${spec#*:}"
  card_dir="$(dirname "$card_path")"
  if [[ "$card_dir" != "/" ]] && [[ ! " ${made_dirs[*]-} " == *" $card_dir "* ]]; then
    run mmd -i "$img" "::$card_dir" 2>/dev/null || true
    made_dirs+=("$card_dir")
  fi
done

for spec in "$@"; do
  local_path="${spec%%:*}"
  card_path="${spec#*:}"
  run mcopy -i "$img" "$local_path" "::$card_path"
  echo "$local_path -> $card_path"
done

size_bytes=$((size_mb * 1024 * 1024))
cat > "$out_dir/sdcard.repl" <<EOF
// Generated by scripts/wio_renode_sdcard.bash -- an SD card image (this file
// alongside it, sdcard.img) wired onto sercom6_spi. Load *after* the base
// platform: machine LoadPlatformDescription @app/wio/renode/wio_terminal.repl
// then machine LoadPlatformDescription @$out_dir/sdcard.repl
// SD.SDCard already implements the real SD-over-SPI wire protocol (spiMode:
// true) -- ADR 94's original research missed this (it only checked that the
// card-storage class existed, not that it had an SPI front end); no new
// peripheral was needed for this half of P4.
sdcard: SD.SDCard @ sercom6_spi
    imageFile: "$img"
    capacity: $size_bytes
    persistent: true
    spiMode: true
EOF
echo "Wrote $out_dir/sdcard.repl"
