// Generated by scripts/native_binding_split.rb (ADR 0263).
// Frame-independent entry points of the RGSS native bindings.
#pragma once

#include <mruby.h>

namespace rgss {

mrb_value audio_update_direct(mrb_state* M, mrb_value self);
mrb_value bgm_fade_direct(mrb_state* M, mrb_value self, mrb_int ms);
mrb_value bgm_pan_direct(mrb_state* M, mrb_value self, mrb_int pan);
mrb_value bgm_pos_direct(mrb_state* M, mrb_value self);
mrb_value bgm_stop_direct(mrb_state* M, mrb_value self);
mrb_value bgm_volume_direct(mrb_state* M, mrb_value self, mrb_int volume);
mrb_value bgs_fade_direct(mrb_state* M, mrb_value self, mrb_int ms);
mrb_value bgs_pos_direct(mrb_state* M, mrb_value self);
mrb_value bgs_stop_direct(mrb_state* M, mrb_value self);
mrb_value bmp_begin_load_direct(mrb_state* M, mrb_value self);
mrb_value bmp_blur_direct(mrb_state* M, mrb_value self);
mrb_value bmp_decoder_ran_direct(mrb_state* M, mrb_value self);
mrb_value bmp_init_copy_direct(mrb_state* M, mrb_value self, mrb_value other);
mrb_value bmp_init_size_direct(mrb_state* M,
                               mrb_value self,
                               mrb_int w,
                               mrb_int h);
mrb_value bmp_load_error_direct(mrb_state* M, mrb_value self);
mrb_value bmp_stbi_error_direct(mrb_state* M, mrb_value self);
mrb_value bmp_text_size_direct(mrb_state* M,
                               mrb_value self,
                               const char* s,
                               mrb_int len);
mrb_value bmp_transition_alpha_direct(mrb_state* M,
                                      mrb_value self,
                                      mrb_value map_v,
                                      mrb_float prog,
                                      mrb_float vague);
mrb_value can_play_mem_direct(mrb_state* M, mrb_value self);
mrb_value color_dump_direct(mrb_state* M, mrb_value self);
mrb_value color_eq_direct(mrb_state* M, mrb_value self, mrb_value o);
mrb_value color_load_direct(mrb_state* M,
                            mrb_value self,
                            const char* p,
                            mrb_int len);
mrb_value color_to_s_direct(mrb_state* M, mrb_value self);
mrb_value default_font_path_m_direct(mrb_state* M, mrb_value self);
mrb_value gfx_frame_reset_direct(mrb_state* M, mrb_value self);
mrb_value input_push_direct(mrb_state* M,
                            mrb_value self,
                            mrb_int key,
                            mrb_bool press);
mrb_value me_fade_direct(mrb_state* M, mrb_value self, mrb_int ms);
mrb_value me_stop_direct(mrb_state* M, mrb_value self);
mrb_value midi_available_direct(mrb_state* M, mrb_value self);
mrb_value mouse_pressed_m_direct(mrb_state* M, mrb_value self);
mrb_value mouse_x_m_direct(mrb_state* M, mrb_value self);
mrb_value mouse_y_m_direct(mrb_state* M, mrb_value self);
mrb_value plane_set_bmp_direct(mrb_state* M, mrb_value self, mrb_value bmp);
mrb_value plane_set_ox_direct(mrb_state* M, mrb_value self, mrb_int ox);
mrb_value plane_set_oy_direct(mrb_state* M, mrb_value self, mrb_int oy);
mrb_value plane_set_tone_direct(mrb_state* M, mrb_value self, mrb_value v);
mrb_value plane_set_zoom_x_direct(mrb_state* M, mrb_value self, mrb_float z);
mrb_value plane_set_zoom_y_direct(mrb_state* M, mrb_value self, mrb_float z);
mrb_value rect_dump_direct(mrb_state* M, mrb_value self);
mrb_value rect_empty_direct(mrb_state* M, mrb_value self);
mrb_value rect_eq_direct(mrb_state* M, mrb_value self, mrb_value o);
mrb_value rect_s_load_direct(mrb_state* M,
                             mrb_value self,
                             const char* p,
                             mrb_int len);
mrb_value rect_to_s_direct(mrb_state* M, mrb_value self);
mrb_value se_stop_direct(mrb_state* M, mrb_value self);
mrb_value spr_set_angle_direct(mrb_state* M, mrb_value self, mrb_float deg);
mrb_value spr_set_blend_type_direct(mrb_state* M, mrb_value self, mrb_int t);
mrb_value spr_set_bush_depth_direct(mrb_state* M, mrb_value self, mrb_int d);
mrb_value spr_set_mirror_direct(mrb_state* M, mrb_value self, mrb_bool m);
mrb_value spr_set_opacity_direct(mrb_state* M, mrb_value self, mrb_int opa);
mrb_value spr_set_src_rect_direct(mrb_state* M, mrb_value self, mrb_value v);
mrb_value spr_set_tone_direct(mrb_state* M, mrb_value self, mrb_value v);
mrb_value spr_set_zoom_x_direct(mrb_state* M, mrb_value self, mrb_float z);
mrb_value spr_set_zoom_y_direct(mrb_state* M, mrb_value self, mrb_float z);
mrb_value table_dim_direct(mrb_state* M, mrb_value self);
mrb_value table_dump_direct(mrb_state* M, mrb_value self);
mrb_value table_load_direct(mrb_state* M,
                            mrb_value self,
                            const char* p,
                            mrb_int len);
mrb_value table_xsize_direct(mrb_state* M, mrb_value self);
mrb_value table_ysize_direct(mrb_state* M, mrb_value self);
mrb_value table_zsize_direct(mrb_state* M, mrb_value self);
mrb_value tilemap_bitmaps_direct(mrb_state* M, mrb_value self);
mrb_value tilemap_set_flags_direct(mrb_state* M, mrb_value self, mrb_value v);
mrb_value tilemap_set_map_data_direct(mrb_state* M,
                                      mrb_value self,
                                      mrb_value v);
mrb_value tilemap_set_ox_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value tilemap_set_oy_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value tilemap_set_priorities_direct(mrb_state* M,
                                        mrb_value self,
                                        mrb_value v);
mrb_value tilemap_set_tileset_direct(mrb_state* M, mrb_value self, mrb_value v);
mrb_value tilemap_update_direct(mrb_state* M, mrb_value self);
mrb_value tilemap_vx_table_leg_quads_direct(mrb_state* M,
                                            mrb_value self,
                                            mrb_int tile_id);
mrb_value tone_dump_direct(mrb_state* M, mrb_value self);
mrb_value tone_eq_direct(mrb_state* M, mrb_value self, mrb_value o);
mrb_value tone_load_direct(mrb_state* M,
                           mrb_value self,
                           const char* p,
                           mrb_int len);
mrb_value tone_to_s_direct(mrb_state* M, mrb_value self);
mrb_value tts_available_direct(mrb_state* M, mrb_value self);
mrb_value tts_speak_direct(mrb_state* M, mrb_value self, const char* text);
mrb_value tts_stop_direct(mrb_state* M, mrb_value self);
mrb_value vp_ox_direct(mrb_state* M, mrb_value self);
mrb_value vp_oy_direct(mrb_state* M, mrb_value self);
mrb_value vp_set_ox_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value vp_set_oy_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value vp_set_rect_direct(mrb_state* M, mrb_value self, mrb_value rv);
mrb_value vp_set_tone_direct(mrb_state* M, mrb_value self, mrb_value t);
mrb_value window_set_back_opacity_direct(mrb_state* M,
                                         mrb_value self,
                                         mrb_int v);
mrb_value window_set_contents_opacity_direct(mrb_state* M,
                                             mrb_value self,
                                             mrb_int v);
mrb_value window_set_opacity_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value window_set_openness_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value window_set_ox_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value window_set_oy_direct(mrb_state* M, mrb_value self, mrb_int v);
mrb_value window_set_stretch_direct(mrb_state* M, mrb_value self, mrb_bool v);
mrb_value window_set_tone_direct(mrb_state* M, mrb_value self, mrb_value t);
mrb_value window_set_viewport_direct(mrb_state* M,
                                     mrb_value self,
                                     mrb_value vp);
mrb_value window_title_get_m_direct(mrb_state* M, mrb_value self);
mrb_value window_title_set_m_direct(mrb_state* M,
                                    mrb_value self,
                                    mrb_value title);
mrb_value zlib_inflate_direct(mrb_state* M,
                              mrb_value self,
                              const char* ptr,
                              mrb_int len);

}  // namespace rgss
