# PlatformIO pre-build script: embed data/maix-hello into the firmware.
#
# The K210 has no filesystem until an SD card is mounted (and Renode models
# no SD controller at all), so the game the maix_game firmware boots lives
# in flash instead: this walks data/maix-hello and emits one C array per
# file plus a path table, which app/wio/src/maix_embed.cxx serves through
# newlib _open/_read/... behind GAME_DIR=/game. Regenerated every build
# into the environment's own build tree (never checked in); the game
# sources themselves live in data/maix-hello (see its README and
# scripts/gen-maix-hello-game.rb).
import os

Import("env")  # noqa: F821  (injected by PlatformIO/SCons)

REPO_ROOT = env["PROJECT_DIR"]
GAME_DIR = os.path.join(REPO_ROOT, "data", "maix-hello")
GAME_PREFIX = "/game"
# BUILD_DIR holds construction variables ($PROJECT_BUILD_DIR/$PIOENV) --
# subst them first, or the header lands in a literal $-named directory.
OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "generated")
OUT_H = os.path.join(OUT_DIR, "maix_game_data.h")


def c_bytes(path):
    with open(path, "rb") as f:
        data = f.read()
    return ", ".join(str(b) for b in data), len(data)


def main():
    entries = []
    for root, _dirs, files in os.walk(GAME_DIR):
        for name in sorted(files):
            full = os.path.join(root, name)
            rel = os.path.relpath(full, GAME_DIR).replace(os.sep, "/")
            entries.append((GAME_PREFIX + "/" + rel, full))
    entries.sort()
    os.makedirs(OUT_DIR, exist_ok=True)
    parts = [
        "// Generated by app/maix/embed_game.py from data/maix-hello -- do not edit.",
        "#pragma once",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
    ]
    table = []
    for i, (vpath, full) in enumerate(entries):
        blob, size = c_bytes(full)
        parts.append("static const uint8_t kMaixEmbed%d[] = {%s};" % (i, blob))
        parts.append("static const size_t kMaixEmbed%dLen = %d;" % (i, size))
        table.append('    {"%s", kMaixEmbed%d, kMaixEmbed%dLen},' % (vpath, i, i))
    parts += [
        "",
        "typedef struct {",
        "  const char* path;",
        "  const uint8_t* data;",
        "  size_t len;",
        "} MaixEmbedFile;",
        "",
        "static const MaixEmbedFile kMaixEmbedFiles[] = {",
    ]
    parts.extend(table)
    parts += [
        "};",
        "",
        "static const size_t kMaixEmbedFileCount = %d;" % len(entries),
        "",
    ]
    with open(OUT_H, "w") as f:
        f.write("\n".join(parts) + "\n")
    print("embed_game: %d files -> %s" % (len(entries), OUT_H))


main()
env.Append(CPPPATH=[OUT_DIR])
